# Generated by Django 2.1.7 on 2019-07-17 22:13

import challenges.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0006_challengesubmission_errors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_auto_20190411_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChallengeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('best_result', models.CharField(blank=True, choices=[(challenges.models.Result('Erro'), 'Erro'), (challenges.models.Result('OK'), 'OK')], max_length=5)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userchallengereport',
            unique_together={('user', 'challenge')},
        ),
    ]
